version: "3.3"
services:
    # docker-compose up --build --force-recreate web
    #   --force-recreate    Recreate containers even if their configuration and image haven't changed.
    #   --build             Build images before starting containers.
    web:
        build: .
        ports:
            - "9200:9200"
        depends_on: 
            - "gensim"
        command: ["./wait-for-it.sh", "gensim:9100", "--", "python3", "src/run.py"]
    corenlp:
        image: "nlpbox/corenlp"
        ports:
            - "9000:9000"
    spacyapi:
        image: jgontrum/spacyapi:en_v2
        ports:
          - "8080:80"
        restart: always
    gensim:
        image: "justiceo/gensim-docker"
        ports:
            - "9100:9100"