version: "3.3"
services:
    # docker-compose up --build --force-recreate web
    #   --force-recreate    Recreate containers even if their configuration and image haven't changed.
    #   --build             Build images before starting containers.
    web:
        build: .
        ports:
            - "9200:9200"
        depends_on: 
            - "gensim"
        command: ["./wait-for-it.sh", "gensim:9100", "--", "python3", "src/run.py"]
        restart: "on-failure"
    text:
        # test:  curl -X GET -k http://127.0.0.1:9300 -H "Content-Type: application/json" -d '{"url": "https://en.wikipedia.org/wiki/Oxygen"}' 
        image: "justiceo/text-extraction:latest"
        ports:
            - "9300:9300"
    corenlp:
        # test: curl --data 'The quick brown fox jumped over the lazy dog.' 'http://localhost:9000/?properties={%22annotators%22%3A%22tokenize%2Cssplit%2Cpos%22%2C%22outputFormat%22%3A%22json%22}' -o -
        image: "nlpbox/corenlp"
        ports:
            - "9000:9000"
    spacyapi:
        image: jgontrum/spacyapi:en_v2
        ports:
          - "8080:80"
        restart: always
    gensim:
        image: "justiceo/gensim-docker"
        ports:
            - "9100:9100"